services:
  km:
    image: kernelmemory/service
    restart: always
    depends_on:
      - qdrant
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9001:9001"
    volumes:
      - ./appsettings.json:/app/appsettings.Development.json
      - ./_files:/app/_files
      - ./_queues:/app/_queues
      - ./_vectors:/app/_vectors

  qdrant:
    image: qdrant/qdrant
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./_qdrant_data:/qdrant/storage